### ISSUE TITLE
Update npm package.

### ISSUE THREAD

**Issue by tripodsgames** [MatthewWid/better-sse#18]
I loved this library, it makes it much easier to use sse, however, would it be possible to update the package in npm? 

![image](https://user-images.githubusercontent.com/11417768/124360955-e67e1500-dc02-11eb-9678-755da5f61e29.png)

**Comment by MatthewWid** [comment]
Hey there. Thanks so much for reporting this issue!

This is now fixed in version `0.4.0` published on npm along with some new features such as an automatic keep-alive mechanism.

```bash
npm install better-sse@latest
```
