### ISSUE TITLE
How do I initiate session disconnection from the server?

### ISSUE THREAD

**Issue by panta82** [MatthewWid/better-sse#47]
I know I can listen to `'disconnected'` event to handle a client going away.

But how can I kick a client from the server?

**Comment by MatthewWid** [comment]
To disconnect a client you can simply call `res.end()`. However, this will cause the client to attempt to reconnect to the server after a short timeout, so you'll need to implement an event that makes the client disconnect themselves.

As an example, add a `disconnect` event that makes the client close its own connection:

```typescript
const source = new EventSource("/sse");

source.addEventListener("disconnect", () => {
  source.close();
});
```

Then from the server you can simply send that event whenever you want to disconnect them:

```typescript
session.push(null, "disconnect");
```

Also keep in mind you can send an [HTTP 204 response code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204) to ask a client to stop reconnecting.

**Comment by panta82** [comment]
Thanks for the great reply @MatthewWid 
I am still getting my head around EventSourcing, didn't occur to me client might try to reconnect.
I'll re-architect my thing a bit given what you said.
