### ISSUE TITLE
[QUESTION] - Session Metadata & Disconnection

### ISSUE THREAD

**Issue by go4cas** [MatthewWid/better-sse#58]
I'm really keen on using this library in a real-time dashboard stack, using unjs' Nitro server. I just a few questions (which I could not find answers for in the docs):

1. I would ideally like to add some metadata to each connection (`Session`). This could include data like user-agent, user identifier (internal ID, email, IP address, etc), connection timestamp, etc. Is this supported at the moment?
2. I intend to include an Admin module in my app, whereby connected clients will be listed, by channel. I would prefer to have the feature to manually disconnect a client. is this available?

**Comment by MatthewWid** [comment]
1. Yes. You can use the [`Session#state`](https://github.com/MatthewWid/better-sse/blob/master/docs/api.md#sessionstate-state) property to add metadata to sessions (as well as [channels](https://github.com/MatthewWid/better-sse/blob/master/docs/api.md#channelstate-state)).

    If you're using TypeScript, you can add type information to the metadata object via generics when you create the session:

    ```typescript
    const session = createSession<{email: string}>();
    
    session.state.email = "example@gmail.com";

    session.state.email = 12345; // TypeScript Error: Type 'number' is not assignable to type 'string'.
    ```

   Or you can change the default session state for _all_ sessions using [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) and [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-interfaces) and adding properties to the `DefaultSessionState` interface.

2. See #47.
