### ISSUE TITLE
How can we pass headers 

### ISSUE THREAD

**Issue by dpvenkatesh** [MatthewWid/better-sse#63]
Can you add an example of passing Authorization headers while connecting to see from the client.

**Comment by MatthewWid** [comment]
This library manages the server-end of SSE, only.

If you want to be able to send headers from the client you should use an [`EventSource`](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) library that allows you to do so. [`EventSource/eventsource`](https://github.com/EventSource/eventsource) and [`Yaffle/EventSource`](https://github.com/Yaffle/EventSource) are two good options.
