### ISSUE TITLE
Cannot push data to a non-active session.

### ISSUE THREAD

**Issue by punkpeye** [MatthewWid/better-sse#69]
I am debugging an odd case where if I have multiple SSE sessions, one of them inevitably starts failing with an error:

> SseError: better-sse: Cannot push data to a non-active session.

Any clue how could I be getting in this situation and how to prevent it?

**Comment by MatthewWid** [comment]
This error means you are attempting to call the [`Session#push`](https://github.com/MatthewWid/better-sse/blob/master/docs/api.md#sessionpush-data-unknown-eventname-string-eventid-string--this) method (or calling it indirectly via [`stream`](https://github.com/MatthewWid/better-sse/blob/master/docs/api.md#sessionstream-stream-readable-options-object--promiseboolean) or [`iterate`](https://github.com/MatthewWid/better-sse/blob/master/docs/api.md#sessioniterate-iterable-iterable--asynciterable-options-object--promisevoid)) after it has been disconnected from the client.

Can you elaborate on what you mean by "multiple SSE sessions"? This is hard to debug without a code sample.

If you are storing multiple sessions somewhere outside of your route handler and then pushing to them directly, you might want to consider using [channels](https://github.com/MatthewWid/better-sse/blob/master/docs/api.md) instead as they prevent you from being able to push events to disconnected sessions.

In the mean time, you can add a check that the [`Session#isConnected`](https://github.com/MatthewWid/better-sse/blob/master/docs/api.md#sessionisconnected-boolean) property is `true` before you attempt to push to it.
