### ISSUE TITLE
Update Session#writeAndFlushHeaders to also be able to give an HTTP response code.

### ISSUE THREAD

**Issue by MatthewWid** [MatthewWid/better-sse#7]
Instead of only being able to give an object with headers, the `Session#writeAndFlushHeaders` method should also take an HTTP response code to send so as to let the implementation send an `HTTP 204 No Content` response to indicate to the client that they should stop reconnecting, [as per the spec](https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events-intro).

**Comment by abhi12299** [comment]
Hey, I have worked out a possible solution to this but I am unable to get my code running with an express application. How exactly do I do that?

**Comment by MatthewWid** [comment]
Thanks so much for wanting to contirbute!

> Hey, I have worked out a possible solution to this but I am unable to get my code running with an express application. How exactly do I do that?

I have now added an `examples/` directory that has [an example of a basic setup](https://github.com/MatthewWid/better-sse/tree/398f1a59313e4a38febed715f3feb42d9d70c2c3/examples/getting-started) using the package (essentially a full demo of the 'Getting Started' section from the docs).

To run, you can simply enter the directory (`examples/getting-started/`), install the dependencies (`yarn`) and start in development mode (`yarn run dev`).

If you want to work on the module itself whilst using the demo, do following from the project root:

1. `yarn` - Install dependencies.
2. `yarn run typedefs && yarn run dev` - Output type declarations and start in development mode to watch for changes and automatically rebuild.
3. `cd examples/getting-started` - (In another terminal) Move into the example project directory.
4. `yarn` - Install demo dependencies.
5. `yarn run dev` - Run in development mode to also watch for changes and re-run.
6. `import sse from "better-sse";` -> `import sse from "../..";` in `server.ts` to use your local module instead of the one up on npm.

I think the implementation of this feature should mimic that of the [Express/HTTP API](https://nodejs.org/api/http.html#http_response_writehead_statuscode_statusmessage_headers) as that's what most users would be used to:

```javascript
Session#writeAndFlushHeaders(statusCode, headers)
```

**Comment by abhi12299** [comment]
Thank you for the detailed explanation. I'll get it working and raise a PR.
I've also implemented the streaming functionality. Will test that as well.
