### ISSUE TITLE
Hapi support

### ISSUE THREAD

**Issue by damusix** [MatthewWid/better-sse#76]
This topic of SSE comes up here and there in Hapi slack. Would be cool to see hapi support. Hapi offers the raw req/res from the `http` built-in, and allows you to fully take over the request handling using the `h.abandon` symbol. Might be interesting to see a decoration that handles the usage:

```js
{
  ...,
  handler(req, h) {
    // implicitly returns h.abandon. Pushes are handled in the callback
    return h.betterSse(req.raw, (sse) => {

      sse.push(...);
    });
  }
}
```

Above is pseudocode but just an endresult idea that might be interesting.

**Comment by MatthewWid** [comment]
> Hapi offers the raw req/res from the http built-in, and allows you to fully take over the request handling using the h.abandon symbol.

This package should work out of the box in that case.

I've now added an example of using Hapi in [recipes section](https://matthewwid.github.io/better-sse/reference/recipes/#hapi) of the documentation 🙂.
